version: "3.9"

services:
  api:
    build:
      context: ./apps/api
      target: prod
    container_name: webhux-api
    ports:
      - "8080:8080"
    env_file:
      - ./apps/api/.env
    restart: unless-stopped

  webhook:
    build:
      context: ./apps/webhook
      target: prod
    container_name: webhux-webhook
    ports:
      - "5000:5000"
    env_file:
      - ./apps/webhook/.env
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
    container_name: webhux-web
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    environment:
      NODE_ENV: production
    depends_on:
      - api
      - webhook
    restart: unless-stopped