services:

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: webhook-api
    ports:
      - "8080:8080"
    command: npm run dev
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 8080